name: Publish Gem

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  publish:
    uses: ./.github/workflows/publish-gem-template.yml
    with:
      service_id: lib
      gemspec_path: joist-events.gemspec
      aws_region: us-east-1
