name: Publish Gem (Manual)

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/publish-gem-template.yml
    with:
      service_id: lib
      gemspec_path: joist-events.gemspec
      aws_region: us-east-1
